### ISSUE TITLE
Error when executing `npm run dev`

### ISSUE THREAD

**Issue by flovogt** [hschaefer123/ui5-vitepress#1]
Hi @hschaefer123,
I have cloned the repository and installed the npm dependencies as described in the readme.
However, I get following error message:

```bash
▶ npm run dev

> ui5-vitepress@1.0.0 dev
> vitepress --open

failed to start server. error:
Error: [shikiji] Language `cds` not found, you may need to load it first
    at Object.getLangGrammar (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:668:13)
    at codeToThemedTokens (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4498:28)
    at file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4625:26
    at Array.map (<anonymous>)
    at codeToTokensWithThemes (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4625:15)
    at codeToHast (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4684:25)
    at codeToHtml (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4882:23)
    at Object.codeToHtml (file:///Users/myuser/git/ui5-vitepress/node_modules/shikiji/dist/core.mjs:4894:37)
    at Object.highlight (file:///Users/myuser/git/ui5-vitepress/node_modules/vitepress/dist/node/serve-ao1ovSY4.js:46663:37)
    at default_rules.fence (file:///Users/myuser/git/ui5-vitepress/node_modules/vitepress/dist/node/serve-ao1ovSY4.js:34803:27)
```

Can you confirm that this happens also on your side?

I tried it with node version (18 and 20).

**Comment by hschaefer123** [comment]
Hi Florian,

i am currently working at the same issue with the breaking changes with 
"vitepress": "^1.0.0-rc.31",
from the former
"vitepress": "^1.0.0-rc.20",

To get it running you can use exactly rc20 

The changes from shiki to shikiji.
I will fix this the next days, but you can change ``config.ts`` using the new way of loading syntaxes.

At the top, add
```
import { promises as fs } from 'node:fs'
import type { LanguageInput, IRawGrammar } from 'shikiji'
const loadSyntax = async (file: string, name: string, alias: string = name): Promise<LanguageInput> => {
  const src = await fs.readFile(join(__dirname, file))
  const grammar: IRawGrammar = JSON.parse(src.toString())
  return { name, aliases: [name, alias], ...grammar }
}
```

and in the config, use the new way of loading syntaxes (or just comment the used languages out).

```
markdown: {
    // Add support for your own languages.
    // https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki
    languages: [
      // https://github.com/SAP-samples/vscode-abap-cds/blob/main/syntaxes/cds.tmLanguage.json
      await loadSyntax('syntaxes/abapcds.tmLanguage.json', 'abapcds'),
      // https://github.com/SAP/cds-textmate-grammar/blob/main/syntaxes/cds.tmLanguage.json
      await loadSyntax('syntaxes/cds.tmLanguage.json', 'cds'),
      // https://github.com/mechatroner/vscode_rainbow_csv/blob/master/syntaxes/csv.tmLanguage.json
      await loadSyntax('syntaxes/csv.tmLanguage.json', 'csv'),
      // https://github.com/mechatroner/vscode_rainbow_csv/blob/master/syntaxes/csv.tmLanguage.json
      await loadSyntax('syntaxes/scsv.tmLanguage.json', 'csvs'),
      // https://github.com/Huachao/vscode-restclient/blob/master/syntaxes/http.tmLanguage.json
      await loadSyntax('syntaxes/http.tmLanguage.json', 'rest'),
    ],
```

Sadly they still introduce breaking changes even in the RC!

Regards Holger

**Comment by hschaefer123** [comment]
Just updated to 1.0.1, so the new version should work with a fresh new install and latest version of vitepress.

Thanks for reporting.

Regards
Holger

**Comment by flovogt** [comment]
Thanks a lot @hschaefer123. Works like a charm.
